### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by deguchi** [barodeur/react-native-nfc-ios#16]
Hi, thank you for your  nice module.

I have make new react native@0.48.0 project and install your module.
but build failed.
Mac OSX 10.12.6 and Xcode 9 GM.
Here is my build log:

>In file included from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:1:
In file included from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.h:4:
In file included from ../../react-native/React/Modules/RCTEventEmitter.h:10:
In file included from /Users/deguchi/Library/Developer/Xcode/DerivedData/touchappios-fzihoyzjmwjhjreyerryunnsadon/Build/Products/Debug-iphonesimulator/include/React/RCTBridge.h:13:
/Users/deguchi/Library/Developer/Xcode/DerivedData/touchappios-fzihoyzjmwjhjreyerryunnsadon/Build/Products/Debug-iphonesimulator/include/React/RCTBridgeModule.h:54:16: error: redefinition of 'RCTMethodInfo'
typedef struct RCTMethodInfo {
               ^
In file included from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:1:
In file included from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.h:3:
../../react-native/React/Base/RCTBridgeModule.h:54:16: note: previous definition is here
typedef struct RCTMethodInfo {
               ^
In file included from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:1:
In file included from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.h:4:
In file included from ../../react-native/React/Modules/RCTEventEmitter.h:10:
In file included from /Users/deguchi/Library/Developer/Xcode/DerivedData/touchappios-fzihoyzjmwjhjreyerryunnsadon/Build/Products/Debug-iphonesimulator/include/React/RCTBridge.h:13:
/Users/deguchi/Library/Developer/Xcode/DerivedData/touchappios-fzihoyzjmwjhjreyerryunnsadon/Build/Products/Debug-iphonesimulator/include/React/RCTBridgeModule.h:58:3: error: typedef redefinition with different types ('struct (anonymous struct at /Users/deguchi/Library/Developer/Xcode/DerivedData/touchappios-fzihoyzjmwjhjreyerryunnsadon/Build/Products/Debug-iphonesimulator/include/React/RCTBridgeModule.h:54:16)' vs 'struct RCTMethodInfo')
} RCTMethodInfo;
  ^
In file included from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:1:
In file included from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.h:3:
../../react-native/React/Base/RCTBridgeModule.h:58:3: note: previous definition is here
} RCTMethodInfo;
  ^
In file included from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:1:
In file included from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.h:4:
In file included from ../../react-native/React/Modules/RCTEventEmitter.h:10:
In file included from /Users/deguchi/Library/Developer/Xcode/DerivedData/touchappios-fzihoyzjmwjhjreyerryunnsadon/Build/Products/Debug-iphonesimulator/include/React/RCTBridge.h:13:
/Users/deguchi/Library/Developer/Xcode/DerivedData/touchappios-fzihoyzjmwjhjreyerryunnsadon/Build/Products/Debug-iphonesimulator/include/React/RCTBridgeModule.h:65:11: warning: duplicate protocol definition of 'RCTBridgeModule' is ignored [-Wduplicate-protocol]
@protocol RCTBridgeModule <NSObject>
          ^
In file included from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:1:
In file included from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.h:3:
../../react-native/React/Base/RCTBridgeModule.h:65:11: note: previous definition is here
@protocol RCTBridgeModule <NSObject>
          ^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:6:28: warning: 'NFCNDEFReaderSession' is partial: introduced in iOS 11.0 [-Wunguarded-availability-new]
    NSMapTable<NSNumber *, NFCNDEFReaderSession *> *nfcNDEFReaderSessionsFromId;
                           ^
In module 'CoreNFC' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/CoreNFC.framework/Headers/NFCNDEFReaderSession.h:113:12: note: 'NFCNDEFReaderSession' has been explicitly marked partial here
@interface NFCNDEFReaderSession : NFCReaderSession
           ^
In file included from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:1:
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.h:10:12: note: annotate 'ReactNativeNfcIos' with an availability attribute to silence
@interface ReactNativeNfcIos : RCTEventEmitter <RCTBridgeModule>
           ^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:7:16: warning: 'NFCNDEFReaderSession' is partial: introduced in iOS 11.0 [-Wunguarded-availability-new]
    NSMapTable<NFCNDEFReaderSession *, NSNumber *> *nfcNDEFReaderSessionsToId;
               ^
In module 'CoreNFC' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/CoreNFC.framework/Headers/NFCNDEFReaderSession.h:113:12: note: 'NFCNDEFReaderSession' has been explicitly marked partial here
@interface NFCNDEFReaderSession : NFCReaderSession
           ^
In file included from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:1:
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.h:10:12: note: annotate 'ReactNativeNfcIos' with an availability attribute to silence
@interface ReactNativeNfcIos : RCTEventEmitter <RCTBridgeModule>
           ^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:37:24: warning: 'NFCNDEFReaderSession' is partial: introduced in iOS 11.0 [-Wunguarded-availability-new]
- (void)readerSession:(NFCNDEFReaderSession *)session
                       ^
In module 'CoreNFC' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/CoreNFC.framework/Headers/NFCNDEFReaderSession.h:113:12: note: 'NFCNDEFReaderSession' has been explicitly marked partial here
@interface NFCNDEFReaderSession : NFCReaderSession
           ^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:37:1: note: annotate 'readerSession:didDetectNDEFs:' with an availability attribute to silence
- (void)readerSession:(NFCNDEFReaderSession *)session
^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:38:32: warning: 'NFCNDEFMessage' is partial: introduced in iOS 11.0 [-Wunguarded-availability-new]
       didDetectNDEFs:(NSArray<NFCNDEFMessage *> *)messages {
                               ^
In module 'CoreNFC' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/CoreNFC.framework/Headers/NFCNDEFReaderSession.h:59:12: note: 'NFCNDEFMessage' has been explicitly marked partial here
@interface NFCNDEFMessage : NSObject<NSSecureCoding>
           ^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:37:1: note: annotate 'readerSession:didDetectNDEFs:' with an availability attribute to silence
- (void)readerSession:(NFCNDEFReaderSession *)session
^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:69:24: warning: 'NFCNDEFReaderSession' is partial: introduced in iOS 11.0 [-Wunguarded-availability-new]
- (void)readerSession:(NFCNDEFReaderSession *)session
                       ^
In module 'CoreNFC' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/CoreNFC.framework/Headers/NFCNDEFReaderSession.h:113:12: note: 'NFCNDEFReaderSession' has been explicitly marked partial here
@interface NFCNDEFReaderSession : NFCReaderSession
           ^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:69:1: note: annotate 'readerSession:didInvalidateWithError:' with an availability attribute to silence
- (void)readerSession:(NFCNDEFReaderSession *)session
^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:29:83: warning: 'NFCNDEFReaderSession' is only available on iOS 11.0 or newer [-Wunguarded-availability-new]
    return @{ @"NFCNDEFReaderSession_readingAvailable": [NSNumber numberWithBool:[NFCNDEFReaderSession readingAvailable]]};
                                                                                  ^~~~~~~~~~~~~~~~~~~~
In module 'CoreNFC' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/CoreNFC.framework/Headers/NFCNDEFReaderSession.h:113:12: note: 'NFCNDEFReaderSession' has been explicitly marked partial here
@interface NFCNDEFReaderSession : NFCReaderSession
           ^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:29:83: note: enclose 'NFCNDEFReaderSession' in an @available check to silence this warning
    return @{ @"NFCNDEFReaderSession_readingAvailable": [NSNumber numberWithBool:[NFCNDEFReaderSession readingAvailable]]};
                                                                                  ^~~~~~~~~~~~~~~~~~~~
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:48:107: warning: incompatible pointer to integer conversion sending 'void *' to parameter of type 'NSDataBase64EncodingOptions' (aka 'enum NSDataBase64EncodingOptions') [-Wint-conversion]
                                        @"identifier": [payload.identifier base64EncodedStringWithOptions:nil],
                                                                                                          ^~~
In module 'Foundation' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.h:1:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
In module 'os_object' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/usr/include/dispatch/dispatch.h:59:
In module 'ObjectiveC' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/usr/include/os/object.h:101:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/usr/include/objc/objc.h:108:16: note: expanded from macro 'nil'
#   define nil __DARWIN_NULL
               ^~~~~~~~~~~~~
In module 'Foundation' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.h:1:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/usr/include/sys/_types.h:52:23: note: expanded from macro '__DARWIN_NULL'
#define __DARWIN_NULL ((void *)0)
                      ^~~~~~~~~~~
In module 'Foundation' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.h:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSData.h:133:75: note: passing argument to parameter 'options' here
- (NSString *)base64EncodedStringWithOptions:(NSDataBase64EncodingOptions)options API_AVAILABLE(macos(10.9), ios(7.0), watchos(2.0), tvos(9.0));
                                                                          ^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:49:101: warning: incompatible pointer to integer conversion sending 'void *' to parameter of type 'NSDataBase64EncodingOptions' (aka 'enum NSDataBase64EncodingOptions') [-Wint-conversion]
                                        @"payload": [payload.payload base64EncodedStringWithOptions:nil],
                                                                                                    ^~~
In module 'Foundation' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.h:1:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
In module 'os_object' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/usr/include/dispatch/dispatch.h:59:
In module 'ObjectiveC' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/usr/include/os/object.h:101:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/usr/include/objc/objc.h:108:16: note: expanded from macro 'nil'
#   define nil __DARWIN_NULL
               ^~~~~~~~~~~~~
In module 'Foundation' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.h:1:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/usr/include/sys/_types.h:52:23: note: expanded from macro '__DARWIN_NULL'
#define __DARWIN_NULL ((void *)0)
                      ^~~~~~~~~~~
In module 'Foundation' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.h:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSData.h:133:75: note: passing argument to parameter 'options' here
- (NSString *)base64EncodedStringWithOptions:(NSDataBase64EncodingOptions)options API_AVAILABLE(macos(10.9), ios(7.0), watchos(2.0), tvos(9.0));
                                                                          ^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:50:95: warning: incompatible pointer to integer conversion sending 'void *' to parameter of type 'NSDataBase64EncodingOptions' (aka 'enum NSDataBase64EncodingOptions') [-Wint-conversion]
                                        @"type": [payload.type base64EncodedStringWithOptions:nil],
                                                                                              ^~~
In module 'Foundation' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.h:1:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
In module 'os_object' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/usr/include/dispatch/dispatch.h:59:
In module 'ObjectiveC' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/usr/include/os/object.h:101:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/usr/include/objc/objc.h:108:16: note: expanded from macro 'nil'
#   define nil __DARWIN_NULL
               ^~~~~~~~~~~~~
In module 'Foundation' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.h:1:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/usr/include/sys/_types.h:52:23: note: expanded from macro '__DARWIN_NULL'
#define __DARWIN_NULL ((void *)0)
                      ^~~~~~~~~~~
In module 'Foundation' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.h:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSData.h:133:75: note: passing argument to parameter 'options' here
- (NSString *)base64EncodedStringWithOptions:(NSDataBase64EncodingOptions)options API_AVAILABLE(macos(10.9), ios(7.0), watchos(2.0), tvos(9.0));
                                                                          ^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:44:10: warning: 'NFCNDEFMessage' is only available on iOS 11.0 or newer [-Wunguarded-availability-new]
    for (NFCNDEFMessage *message in messages) {
         ^~~~~~~~~~~~~~
In module 'CoreNFC' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/CoreNFC.framework/Headers/NFCNDEFReaderSession.h:59:12: note: 'NFCNDEFMessage' has been explicitly marked partial here
@interface NFCNDEFMessage : NSObject<NSSecureCoding>
           ^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:44:10: note: enclose 'NFCNDEFMessage' in an @available check to silence this warning
    for (NFCNDEFMessage *message in messages) {
         ^~~~~~~~~~~~~~
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:46:14: warning: 'NFCNDEFPayload' is only available on iOS 11.0 or newer [-Wunguarded-availability-new]
        for (NFCNDEFPayload *payload in message.records) {
             ^~~~~~~~~~~~~~
In module 'CoreNFC' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/CoreNFC.framework/Headers/NFCNDEFReaderSession.h:42:12: note: 'NFCNDEFPayload' has been explicitly marked partial here
@interface NFCNDEFPayload : NSObject<NSSecureCoding>
           ^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:46:14: note: enclose 'NFCNDEFPayload' in an @available check to silence this warning
        for (NFCNDEFPayload *payload in message.records) {
             ^~~~~~~~~~~~~~
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:80:84: warning: sending 'ReactNativeNfcIos *const __strong' to parameter of incompatible type 'id<NFCNDEFReaderSessionDelegate> _Nonnull'
    NFCNDEFReaderSession* session = [[NFCNDEFReaderSession alloc] initWithDelegate:self queue:nil invalidateAfterFirstRead:[invalidateAfterFirstRead boolValue]];
                                                                                   ^~~~
In module 'CoreNFC' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/CoreNFC.framework/Headers/NFCNDEFReaderSession.h:151:68: note: passing argument to parameter 'delegate' here
- (instancetype)initWithDelegate:(id<NFCNDEFReaderSessionDelegate>)delegate queue:(nullable dispatch_queue_t)queue invalidateAfterFirstRead:(BOOL)invalidateAfterFirstRead NS_DESIGNATED_INITIALIZER;
                                                                   ^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:80:5: warning: 'NFCNDEFReaderSession' is only available on iOS 11.0 or newer [-Wunguarded-availability-new]
    NFCNDEFReaderSession* session = [[NFCNDEFReaderSession alloc] initWithDelegate:self queue:nil invalidateAfterFirstRead:[invalidateAfterFirstRead boolValue]];
    ^~~~~~~~~~~~~~~~~~~~
In module 'CoreNFC' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/CoreNFC.framework/Headers/NFCNDEFReaderSession.h:113:12: note: 'NFCNDEFReaderSession' has been explicitly marked partial here
@interface NFCNDEFReaderSession : NFCReaderSession
           ^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:80:5: note: enclose 'NFCNDEFReaderSession' in an @available check to silence this warning
    NFCNDEFReaderSession* session = [[NFCNDEFReaderSession alloc] initWithDelegate:self queue:nil invalidateAfterFirstRead:[invalidateAfterFirstRead boolValue]];
    ^~~~~~~~~~~~~~~~~~~~
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:80:39: warning: 'NFCNDEFReaderSession' is only available on iOS 11.0 or newer [-Wunguarded-availability-new]
    NFCNDEFReaderSession* session = [[NFCNDEFReaderSession alloc] initWithDelegate:self queue:nil invalidateAfterFirstRead:[invalidateAfterFirstRead boolValue]];
                                      ^~~~~~~~~~~~~~~~~~~~
In module 'CoreNFC' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/CoreNFC.framework/Headers/NFCNDEFReaderSession.h:113:12: note: 'NFCNDEFReaderSession' has been explicitly marked partial here
@interface NFCNDEFReaderSession : NFCReaderSession
           ^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:80:39: note: enclose 'NFCNDEFReaderSession' in an @available check to silence this warning
    NFCNDEFReaderSession* session = [[NFCNDEFReaderSession alloc] initWithDelegate:self queue:nil invalidateAfterFirstRead:[invalidateAfterFirstRead boolValue]];
                                      ^~~~~~~~~~~~~~~~~~~~
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:93:5: warning: 'NFCNDEFReaderSession' is only available on iOS 11.0 or newer [-Wunguarded-availability-new]
    NFCNDEFReaderSession *session = [nfcNDEFReaderSessionsFromId objectForKey:sessionId];
    ^~~~~~~~~~~~~~~~~~~~
In module 'CoreNFC' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/CoreNFC.framework/Headers/NFCNDEFReaderSession.h:113:12: note: 'NFCNDEFReaderSession' has been explicitly marked partial here
@interface NFCNDEFReaderSession : NFCReaderSession
           ^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:93:5: note: enclose 'NFCNDEFReaderSession' in an @available check to silence this warning
    NFCNDEFReaderSession *session = [nfcNDEFReaderSessionsFromId objectForKey:sessionId];
    ^~~~~~~~~~~~~~~~~~~~
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:100:5: warning: 'NFCNDEFReaderSession' is only available on iOS 11.0 or newer [-Wunguarded-availability-new]
    NFCNDEFReaderSession *session = [nfcNDEFReaderSessionsFromId objectForKey:sessionId];
    ^~~~~~~~~~~~~~~~~~~~
In module 'CoreNFC' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/CoreNFC.framework/Headers/NFCNDEFReaderSession.h:113:12: note: 'NFCNDEFReaderSession' has been explicitly marked partial here
@interface NFCNDEFReaderSession : NFCReaderSession
           ^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:100:5: note: enclose 'NFCNDEFReaderSession' in an @available check to silence this warning
    NFCNDEFReaderSession *session = [nfcNDEFReaderSessionsFromId objectForKey:sessionId];
    ^~~~~~~~~~~~~~~~~~~~
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:106:5: warning: 'NFCNDEFReaderSession' is only available on iOS 11.0 or newer [-Wunguarded-availability-new]
    NFCNDEFReaderSession *session = [nfcNDEFReaderSessionsFromId objectForKey:sessionId];
    ^~~~~~~~~~~~~~~~~~~~
In module 'CoreNFC' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/CoreNFC.framework/Headers/NFCNDEFReaderSession.h:113:12: note: 'NFCNDEFReaderSession' has been explicitly marked partial here
@interface NFCNDEFReaderSession : NFCReaderSession
           ^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:106:5: note: enclose 'NFCNDEFReaderSession' in an @available check to silence this warning
    NFCNDEFReaderSession *session = [nfcNDEFReaderSessionsFromId objectForKey:sessionId];
    ^~~~~~~~~~~~~~~~~~~~
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:112:5: warning: 'NFCNDEFReaderSession' is only available on iOS 11.0 or newer [-Wunguarded-availability-new]
    NFCNDEFReaderSession *session = [nfcNDEFReaderSessionsFromId objectForKey:sessionId];
    ^~~~~~~~~~~~~~~~~~~~
In module 'CoreNFC' imported from /Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/CoreNFC.framework/Headers/NFCNDEFReaderSession.h:113:12: note: 'NFCNDEFReaderSession' has been explicitly marked partial here
@interface NFCNDEFReaderSession : NFCReaderSession
           ^
/Users/deguchi/apps/touchappios/node_modules/react-native-nfc-ios/ios/ReactNativeNfcIos.m:112:5: note: enclose 'NFCNDEFReaderSession' in an @available check to silence this warning
    NFCNDEFReaderSession *session = [nfcNDEFReaderSessionsFromId objectForKey:sessionId];
    ^~~~~~~~~~~~~~~~~~~~
19 warnings and 2 errors generated.

**Comment by vaxxis** [comment]
you need to change the plugin importing part in the **ReactNativeNfcIos.h** file.

change the RCTBridgeModule part (line 2) with this: 

`#if __has_include(<React/RCTBridgeModule.h>)`
`    #import <React/RCTBridgeModule.h>`
`    #import <React/RCTEventEmitter.h>`
`#else`
`    #import "RCTBridgeModule.h"`
`    #import "RCTEventEmitter.h"`
`#endif`

I've already submited a pull request so hoppefully the problem will be resolved soon in the npm package.

**Comment by barodeur** [comment]
I just published the version `0.1.4` of `react-native-nfc-ios` which should fix this issue. Thanks @vaxxis

**Comment by barodeur** [comment]
I'm closing the issue as builds are passing since the fix was merged.
