### ISSUE TITLE
can it used in create-react-native

### ISSUE THREAD

**Issue by hllhui** [barodeur/react-native-nfc-ios#23]
can it used in create-react-native?

**Comment by barodeur** [comment]
Hi, unfortunately not, you'll have to eject your app if you want to use dependencies with native extentions.

As written in [`create-react-native-app` README](https://github.com/react-community/create-react-native-app#what-are-the-limitations-of-create-react-native-app)

> The main limitation of a Create React Native App project is that it must be written in pure JavaScript and not have any dependencies which rely on custom native code (i.e. ones which require running react-native link to work). This allows the projects to load directly on a phone without native compilation, and also means that it's not necessary to install or use Android Studio or Xcode.
