### ISSUE TITLE
CoreNFC is not avaliable

### ISSUE THREAD

**Issue by vivikenen** [barodeur/react-native-nfc-ios#24]
react-native: ^0.47.0
Device: iPhone 7 plus (iOS 11.3)

I run the example on iPhone 7 plus (iOS 11.3) instead of simulator, but it shows `NFCNDEFReaderSession.readingAvailable` is false. 

Just wondering what other setup I needed to add? 
Does the `.entitlements file` is necessary?

**Comment by barodeur** [comment]
Hey, yes the `.entitlements` file is necessary
