### ISSUE TITLE
signal SIGABRT

### ISSUE THREAD

**Issue by Mcc-0627** [barodeur/react-native-nfc-ios#26]
i got signal SIGABRT whenever i tap the read one tag or read tags. 
I use iphone 7(ios11.4) and xcode 10 beta
![image](https://user-images.githubusercontent.com/19630735/42792534-1045ea42-89b9-11e8-9d60-7c5188d40f71.png)
anyone knows why?

**Comment by bluekyg** [comment]
how to resolved??
