### ISSUE TITLE
react-native-nfc-ios native module cannot be null

### ISSUE THREAD

**Issue by kmbzz** [barodeur/react-native-nfc-ios#31]
!**Uncaught Error** 
When I run my NFC test project ,Native module cannot be null error is occurred.

**Libraries Version**
react native version - ^0.64.2
react-native-nfc-ios version - ^0.1.5

**Platform**
IOS -14.7.1

Kindly help me resolve thes issue.

error screenshoot for referrence.
![Simulator Screen Shot - iPhone 12 - 2021-08-26 at 17 08 49](https://user-images.githubusercontent.com/47659437/130928235-9e17abbd-266f-4e44-be54-a0326cdcadc0.png)

**Comment by barodeur** [comment]
Hi @kmbzz, I've deprecated this package as it might be unsafe to use. I would rather recommend to use `react-native-nfc-masnter` as an alternative.
